FROM {{ARCH.images.base}}

VOLUME /tmp/.X11-unix

ENV DEBIAN_FRONTEND=noninteractive

USER root

RUN \
  mkdir /tmp/.X11-unix && chmod 1777 /tmp/.X11-unix

COPY ./locale /tmp/locale
RUN cd /tmp/locale/ && ./install.sh

# fix: passwd/group file permission were reverted by ibus installation
RUN \
  chmod 666 /etc/passwd /etc/group

USER "${HEADLESS_USER_ID}"
