# https://github.com/Yun-Mao/caddy_docker
# Build Caddy
FROM {{ARCH.images.base}}
RUN apk add --no-cache git gcc musl-dev
RUN mkdir /www /caddy
COPY builder.sh /usr/bin/builder.sh
ARG version="1.0.5"
ARG enable_telemetry="true"
{{#arm32}}
# Explicitly configure go builds for ARM32v6
ENV GOARCH=arm
ENV GOARM=7
{{/arm32}}

RUN VERSION=${version} /bin/sh /usr/bin/builder.sh
