FROM debian:stretch-20200224

ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND noninteractive
RUN apt-get update -qy && apt-get install -qy \
      curl
RUN ["/bin/bash", "-c", "bash < <(curl -s -S -L https://install.direct/go.sh)"]

ENV PATH /usr/bin/v2ray:$PATH
CMD ["v2ray", "-config=/etc/v2ray/config.json"]
