FROM {{IMAGES.BUILD_BASE}}

ENV LANG C.UTF-8
ENV LD_LIBRARY_PATH=/usr/local/lib

# Install builder dependency
RUN apt-get update -qy && apt-get install -qy \
      build-essential

# Build ilclient for raspberry pi
RUN apt-get update -qy && apt-get install -qy \
      libraspberrypi-doc libraspberrypi-dev raspberrypi-kernel-headers

WORKDIR /opt/vc/src/hello_pi/libs/ilclient
RUN make

# Build and install fdk-aac
ENV FDK_AAC_PACKAGE="http://downloads.sourceforge.net/project/opencore-amr/fdk-aac/fdk-aac-0.1.6.tar.gz"
RUN curl -L ${FDK_AAC_PACKAGE} -o /tmp/fdk-aac.tar.gz && \
    tar xvf /tmp/fdk-aac.tar.gz -C /tmp/ && \
    mv /tmp/fdk-aac-0.1.6 /tmp/fdk-aac

WORKDIR /tmp/fdk-aac
RUN ./configure && \
    make -j4 && \
    make install

# Build and install ffmpeg
ENV ffmpeg_version="4.2.2"
RUN curl -L http://ffmpeg.org/releases/ffmpeg-${ffmpeg_version}.tar.gz -o /tmp/ffmpeg.tar.gz && \
    tar xvf /tmp/ffmpeg.tar.gz -C /tmp/ && \
    mv /tmp/ffmpeg-${ffmpeg_version} /tmp/ffmpeg

WORKDIR /tmp/ffmpeg
RUN ./configure \
      --enable-libfdk-aac \
      --disable-debug \
      --disable-shared \
      --disable-ffplay \
      --enable-static && \
    make -j4 && \
    make install

# Sanity Test
RUN ffmpeg -version
