name: 'Build and Push Docker App'
description: 'Greet someone'

runs:
  using: "composite"
  steps:
    -
      name: Checkout repository and submodules
      uses: actions/checkout@v2
    -
      name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build with mbuild
      run: python3 /home/ride/mbuild/utils/build.py docker
    -
      name: Push with mbuild
      run: python3 /home/ride/mbuild/utils/build.py push --only
    -
      name: Deply with mbuild
      run: python3 /home/ride/mbuild/utils/build.py deploy --only
