FROM debian:stretch-20190506-slim



ENV LANG C.UTF-8

RUN apt-get update && apt-get -y upgrade

# https://github.com/fatedier/frp/releases/
ADD frp_0.16.1_linux_amd64.tar.gz /tmp/
RUN mv /tmp/frp_0.16.1_linux_amd64 /root/frp


