
FROM balenalib/rpi-debian:stretch-20190511

RUN [ "cross-build-start" ]

ENV LANG C.UTF-8

RUN apt-get update && apt-get -y upgrade

# https://github.com/fatedier/frp/releases/

ADD frp_0.16.1_linux_arm.tar.gz /tmp/
RUN mv /tmp/frp_0.16.1_linux_arm /root/frp

RUN [ "cross-build-end" ]
