FROM resin/raspberry-pi-debian:stretch-20181024

RUN apt-get update && apt-get -y upgrade

RUN apt-get install -y chromium-browser

# Create chrome user
RUN groupadd -g 1000 chrome \
  && useradd -u 1000 -g chrome -ms /bin/bash chrome

RUN apt-get -y install mesa-utils
RUN apt-get -y install libgl1-mesa-dri

USER chrome
