FROM {{ARCH.images.base}}

ARG arch

ENV LANG C.UTF-8

RUN apt-get update && apt-get install -y \
      `if [ "$arch" = "amd64"  ] ; then echo "chromium" ; else echo "chromium-browser" ; fi` \
      libgl1-mesa-dri \
      mesa-utils \
      && rm -rf /var/lib/apt/lists/*

# Create chromium user
RUN useradd -ms /bin/bash chromium

USER chromium

COPY --chown=chromium ./docker-entrypoint.sh /

ENTRYPOINT ["/docker-entrypoint.sh"]
