FROM {{ARCH.images.base}}

RUN \
  apt-get update && apt-get install -y \
    software-properties-common \
    --no-install-recommends && \
    apt-get update && apt-get install -y \
    hicolor-icon-theme \
    remmina \
    remmina-plugin-rdp \
    remmina-plugin-vnc \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
