# https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple
# https://github.com/pierlon/scrcpy-docker

FROM {{ARCH.images.base}}

ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update -qy

RUN apt install -qy \
  ffmpeg libsdl2-2.0-0 adb wget \
  gcc git pkg-config meson ninja-build libsdl2-dev \
  libavcodec-dev libavdevice-dev libavformat-dev libavutil-dev \
  libusb-1.0-0 libusb-1.0-0-dev

# fix: sudo command not found
RUN apt install -y sudo

RUN git clone --depth 1 https://github.com/Genymobile/scrcpy
#RUN git clone --depth 1 --branch {{IMAGE_VERSION}} https://github.com/Genymobile/scrcpy
WORKDIR /scrcpy

# Build scrcpy
RUN ./install_release.sh

# Create scrcpy user for X11
RUN useradd -m -G video scrcpy

WORKDIR /home/scrcpy

USER scrcpy
