# https://github.com/Genymobile/scrcpy/blob/master/BUILD.md#simple
FROM {{ARCH.images.base}}

ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND noninteractive

# {{#ARCH.is_amd}}
# {{/ARCH.is_amd}}

# {{#ARCH.is_arm}}
# {{/ARCH.is_arm}}

RUN apt-get update -qy
RUN apt install -yq \
  ffmpeg libsdl2-2.0-0 adb wget \
  gcc git pkg-config meson ninja-build \
  libavcodec-dev libavformat-dev libavutil-dev libsdl2-dev

RUN git clone --depth 1 https://github.com/Genymobile/scrcpy
WORKDIR /scrcpy

# install require version for meson
RUN apt install python3-pip
RUN pip3 install meson

# Build scrcpy
RUN ./install_release.sh
