FROM debian:stretch-20190506-slim


ARG VERSION=0.27.0


ENV LANG C.UTF-8

RUN apt-get update -qy && apt-get install -qy \
      build-essential git nasm \
      libomxil-bellagio-dev

WORKDIR /root
RUN git clone https://github.com/FFmpeg/FFmpeg.git --depth 1

WORKDIR /root/FFmpeg
RUN ./configure --arch=armel --target-os=linux --enable-gpl --enable-omx --enable-omx-rpi --enable-nonfree
RUN make -j$(nproc)
RUN make install

